%
% Example for loading the histograms as generated by the program 'dscx'
% Concatenate the histograms as you wish.
%
% Works if you run the script in directory UtilMb (otherwise change paths)
%
clear;
addpath('../DescExtr/UtilMb/Hist');
pthHist = '../DescExtr/Desc/img1.hst';     % histograms for one image

[HFU HFB HSP Nuni Nbiv Nspa] = LoadDescHist(pthHist);

%% --------   Plot Flat Univariate   ---------
figure(1);
subplot(7,1,1);
bar(HFU.Rdg); ylabel('Ridge');

subplot(7,1,2);
bar(HFU.Riv); ylabel('River');

subplot(7,1,3);
bar(HFU.Edg); ylabel('Edge');

subplot(7,1,4);
bar(HFU.Skl); ylabel('Skl');

subplot(7,1,5);
bar(HFU.Rsg); ylabel('RadSig');

subplot(7,1,6);
bar(HFU.Arc); ylabel('Arc');

subplot(7,1,7);
bar(HFU.Str); ylabel('Str');

%% --------   Plot Flat Bivariate   ---------
figure(2);
subplot(7,1,1);
bar(HFB.Rdg); ylabel('Ridge');

subplot(7,1,2);
bar(HFB.Riv); ylabel('River');

subplot(7,1,3);
bar(HFB.Edg); ylabel('Edge');

subplot(7,1,4);
bar(HFB.Skl); ylabel('Skl');

subplot(7,1,5);
bar(HFB.Rsg); ylabel('RadSig');

subplot(7,1,6);
bar(HFB.Arc); ylabel('Arc');

subplot(7,1,7);
bar(HFB.Str); ylabel('Str');

%% --------   Plot Spatial Uni/Biv   ---------
figure(3);
subplot(10,1,1);
bar(HSP.CntUni); ylabel('CntUni');

subplot(10,1,2);
bar(HSP.CntBiv); ylabel('CntBiv');

subplot(10,1,3);
bar(HSP.SklUni); ylabel('SklUni');

subplot(10,1,4);
bar(HSP.SklBiv); ylabel('SklBiv');

subplot(10,1,5);
bar(HSP.RsgUni); ylabel('RsgUni');

subplot(10,1,6);
bar(HSP.RsgBiv); ylabel('RsgBiv');

subplot(10,1,7);
bar(HSP.ArcUni); ylabel('ArcUni');

subplot(10,1,8);
bar(HSP.ArcBiv); ylabel('ArcBiv');

subplot(10,1,9);
bar(HSP.StrUni); ylabel('StrUni');

subplot(10,1,10);
bar(HSP.StrBiv); ylabel('StrBiv');

