%
% Loads the boundary information for regions as generated by the program
% 'dscx' (descriptor extraction).
% 
% Bounding box sizes are already scaled up to original image size.
%
clear;
addpath('../DescExtr/UtilMb/Bon');
addpath('../DescExtr/UtilMb/Bbox');        % contains script p_BoundBbox1

Irgb        = imread('../DescExtr/Imgs/img2.jpg');
%Irgb        = imread('../DescExtr/Imgs/aachen.png');
[ABbox Nbon1 IxX] = LoadBonBboxPyr('../DescExtr/Desc/img1.BonBbox');
[AASP  Nbon2]     = LoadBonAspPyr( '../DescExtr/Desc/img1.BonAsp');
assert(all(Nbon1(:)==Nbon2(:)));
nLev     = length(Nbon1);       % # of pyramid levels

%% -----   Appearance Aspects   -------
% we concatenate across the pyramid, as an exercise:
BboxAll = cat(1,ABbox{:});      % [nBboxes 6] (top/bot/lef/rit/ctr/dth]
Ctr     = BboxAll(:,5);         % contrast of boundaries (not of bboxes)
[Red Grn Blu] = deal(zeros(0,1));
for l = 1:nLev
    Red = [Red; AASP{l}.RGB.Red];
    Grn = [Grn; AASP{l}.RGB.Grn];
    Blu = [Blu; AASP{l}.RGB.Blu];
end
Mapp    = [Ctr Red Grn Blu];    % [nBboxes 5]

%% -----   Plot Bboxes   ------
figure(1); clf;
[nr nc]     = deal(nLev, 2);    % # of rows/cols for subplots
colGray     = [0.6 0.6 0.6];    % default for bounding boxes
bContrast   = 1;                % plots proportional to contrast
for l = 1:nLev
    
    Asp    = AASP{l};
    Box    = ABbox{l};
    nBon   = Nbon1(l);
    
    % -----------   LEFT COLUMN   -------------
    subplot(nr, nc, l*2-1);
    imagesc(Irgb);          % no resizing, because bboxes are scaled already
    
    for b = 1:nBon
        hb = p_BoundBox1(Box(b,:), colGray, 1, bContrast);
        % add color
        red     = Asp.RGB.Red(b) / 255;
        grn     = Asp.RGB.Grn(b) / 255;
        blu     = Asp.RGB.Blu(b) / 255;
        %set(hb, 'edgecolor', [red grn blu]);
    end
    set(gca,'fontsize',5);
    if l==1, title('LEFT: all', 'fontsize', 12); end
    
    % -----------   RIGHT COLUMN   -------------
    subplot(nr, nc, l*2);
    imagesc(Irgb);          % no resizing, because bboxes are scaled already

    for b = 1:nBon

        if Asp.Cvrg(b)>0.01, continue; end % skip larger ones
        %if Asp.Peri(b)>50, continue; end % absolute/not scaled
        
        hb = p_BoundBox1(Box(b,:), colGray);

    end
    set(gca,'fontsize',5);
    if l==1, title('RIGHT: selected', 'fontsize', 12); end
    
    
end

