%
% Loads the boundary pixels for regions as generated by the program
% 'dscx' (descriptor extraction).
% 
clear;
addpath('Bon');

Irgb        = imread('../Imgs/img1.jpg');
%Irgb        = imread('../Imgs/aachen.png');
[AASP  Nbon1]     = LoadBonAspPyr('../Desc/img1.BonAsp');
[APIX  Nbon2 SzM] = LoadBonPixPyr('../Desc/img1.BonPix');
assert(all(Nbon1(:)==Nbon2(:)));
nLev     = length(Nbon1);       % # of pyramid levels

%% -----   Plot Pixels   ------
figure(2); clf;
[nr nc]     = deal(nLev, 2);    % # of rows/cols for subplots
colGray     = [0.6 0.6 0.6];    % default for bounding boxes
for l = 1:nLev
    
    Asp    = AASP{l};
    APix   = APIX{l};
    nBon   = Nbon1(l);
    szV    = SzM(l,1);
    
    % -----------   LEFT COLUMN   -------------
    subplot(nr, nc, l*2-1); hold on;
    %imagesc(Irgb);          % resizing, because bboxes are scaled already
    
    for b = 1:nBon
        ctr = 0;       % contrast
        hb  = p_BoundPix1(APix{b}, szV, colGray, 1, ctr);
        % add color
        red     = Asp.RGB.Red(b) / 255;
        grn     = Asp.RGB.Grn(b) / 255;
        blu     = Asp.RGB.Blu(b) / 255;
        set(hb, 'color', [red grn blu]);
    end
    axis tight;
    set(gca,'fontsize',5);
    if l==1, title('LEFT: all', 'fontsize', 12); end
    
    % -----------   RIGHT COLUMN   -------------
    subplot(nr, nc, l*2); hold on;
    %imagesc(Irgb);          % no resizing, because bboxes are scaled already

    for b = 1:nBon

        if Asp.Cvrg(b)>0.01, continue; end % skip larger ones

        ctr = 0;
        hb  = p_BoundPix1(APix{b}, szV, colGray, 1, ctr);

        % add color
        red     = Asp.RGB.Red(b) / 255;
        grn     = Asp.RGB.Grn(b) / 255;
        blu     = Asp.RGB.Blu(b) / 255;
        set(hb, 'color', [red grn blu]);
    end
    axis tight;
    set(gca,'fontsize',5);
    if l==1, title('RIGHT: selected', 'fontsize', 12); end
    
    
end